import { GetServerSideProps } from "next"
import Head from "next/head"
import Contentful from "contentful"
import { documentToReactComponents } from "@contentful/rich-text-react-renderer"

import Layout from "../../components/Layout"
import { getPost, Post } from "../../services/content"
import { BLOCKS } from "@contentful/rich-text-types"

const renderOptions = {
  renderNode: {
    [BLOCKS.EMBEDDED_ASSET]: (node, children) => (
      <img
        src={node.data.target.fields.file.url}
        height={node.data.target.fields.file.details.height}
        width={node.data.target.fields.file.details.width}
        alt="Content image"
      />
    )
  }
}

type PostProps = {
  post: Contentful.Entry<Post>;
}

export default function PostPage({ post }: PostProps) {
  return (
    <Layout title={post.fields.title}>
      <div>
        <Head>
          <title>News | Coders blog</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className="w-4/5 m-auto min-h-[21.5rem] p-14">
          <div className="w-full max-w-4xl m-auto">
            <img className="w-full object-cover rounded-[1.875rem]" alt="Post thumbnail" src={post.fields.thumbnail.fields.file.url} />
          </div>

          <div className="mt-5 whitespace-pre-wrap">
            {documentToReactComponents(post.fields.content, renderOptions)}
          </div>
        </div>
      </div>
    </Layout>
  )
}

export const getServerSideProps: GetServerSideProps = async ({ query }) => {
  const post = await getPost(query.id as string);

  return {
    props: {
      post
    }
  }
}