import Head from "next/head"
import Layout from "../../components/Layout"

const post = {
  id: 1,
  title: 'Fortnite Challenges Have Grown Stale',
  description: 'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
  thumbnail: 'https://home.multilogica.com.br/wp-content/uploads/2021/03/placeholder.png'
}

export default function Post() {
  return (
    <div>
      <Head>
        <title>News | Coders blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-4/5 m-auto min-h-[21.5rem] p-14">
        <div className="w-full">
          <img className="w-full h-[26rem] object-cover rounded-[1.875rem]" alt="Post thumbnail" src={post.thumbnail} />
        </div>
      </div>
    </div>
  )
}

Post.getLayout = function getLayout(page) {
  return <Layout title={post.title}>{page}</Layout>
}